### ISSUE TITLE
Steps count by tens

### ISSUE THREAD

**Issue by ksyao2002** [natsuite/NatStep#11]
From my testing I found that I have to walk around 17 steps for the pedometer to all of a sudden jump from 0 to 10 steps. I was wondering if there was any way to change the number of oscillations needed per step to detect after say, 5 steps. I think the way I just proposed only works if the pedometer API determines steps from the accelerometer data. Does this API analyze accelerometer data or does it use native pedometers in phones? If it is based off native pedometer, what happens when there is no pedometer in the phone, is there a way to first detect if a pedometer is installed and then provide an response if not?

**Comment by olokobayusuf** [comment]
This is entirely controlled by the hardware pedometer sensor. See the relevant sources:

https://github.com/olokobayusuf/Pedometer-API/blob/e3cce08e8a571adda65f1c0b63534817c51a8791/Android/Pedometer/src/main/java/com/yusufolokoba/pedometer/Pedometer.java#L28-L36

https://github.com/olokobayusuf/Pedometer-API/blob/e3cce08e8a571adda65f1c0b63534817c51a8791/iOS/Pedometer/Pedometer.m#L15-L24

You can check if there is a hardware pedometer available like so:
```csharp
// Check if device has a pedometer
var supported = Pedometer.Implementation.IsSupported;
```
