### ISSUE TITLE
Is there a way to make Step tracking more sensitive? 

### ISSUE THREAD

**Issue by ReGaSLZR** [natsuite/NatStep#13]
Hello there, dev. 😺 

Please help.

Does the plugin offer a way to make the step tracking/counting more sensitive?
It is because of these following scenarios:

- It takes a while before the user's steps are counted right after starting the Pedometer.
- More often than not, while you're walking, you cannot get any Step updates from the plugin in a way that it's per physical step basis. (Example: Current step count is 0, you walk 10 steps. As you take each step, the counter doesn't increase by 1. Instead, the counter just updates itself after the 10th+ step.)

It's really cool that this plugin is free and supports both iOS and Android.
If the step detection could be made more sensitive and this plugin was a paid asset, I'd gladly beg my team to purchase this.

**Comment by olokobayusuf** [comment]
Unfortunately this is not possible. Both of the issues you've pointed out are properties of the hardware pedometers themselves (or at least the native API's that expose them). We have no control over these at the software level (feel free to look through the native sources to better understand what's going on).

**Comment by ReGaSLZR** [comment]
Oh, okay. We understand.
Thank you for the prompt response. 👍
