### ISSUE TITLE
Specify activity permission in Android manifest

### ISSUE THREAD

**Issue by olokobayusuf** [natsuite/NatStep#14]
Android 29 requires this.

**Comment by SimarjitSeasia** [comment]
Please mention the required permissions in android

**Comment by olokobayusuf** [comment]
> Please mention the required permissions in android

I'll check this out. Thanks

**Comment by martin-piliar** [comment]
Hey @olokobayusuf, I know that this is kind of a late response, but today I found out about this asset and had the same issue as you, even with the steps not working on the phone without any errors, so this is the permission you have to add into your android manifest 
`<uses-permission android:name="android.permission.ACTIVITY_RECOGNITION" />`
And then you have to call it inside your app.

**Comment by olokobayusuf** [comment]
Hey @edino525 , I'm working on adding it to the manifest now. To request the permission at runtime, you can use the [Permission class](https://docs.unity3d.com/ScriptReference/Android.Permission.html).
