### ISSUE TITLE
Not able to get Steps count on the demo scene

### ISSUE THREAD

**Issue by SimarjitSeasia** [natsuite/NatStep#15]
Hi,
This is to inform you that I am using your plugin in my app to get the step counts. I am trying to get mobile pedometer steps and show the same to my unity app. But unfortunately, I am not getting any response at all. Even I am not getting any errors it is difficult for me to diagnose the problem. It's very urgent for me to show as my app will be incomplete without this. Actually, I am using the same code on my end. Please suggest to me what extra ee can do to achieve this.
I tried running the demo scene in an empty project also but it never increments the step counts.

**My device has the inbuilt pedometer,
Device name: One plus 7T, Android v 10
Unity 2019.2.17**

public class StepCounter : MonoBehaviour {

        public Text stepText, distanceText;
        private Pedometer pedometer;

        private void Start () {
            // Create a new pedometer
            pedometer = new Pedometer(OnStep);
            // Reset UI
            OnStep(0, 0);
        }

        private void OnStep (int steps, double distance) {
            // Display the values // Distance in feet
            stepText.text = steps.ToString();
            distanceText.text = (distance * 3.28084).ToString("F2") + " ft";
        }

        private void OnDisable () {
            // Release the pedometer
            pedometer.Dispose();
            pedometer = null;
        }
    }
}

**Comment by SimarjitSeasia** [comment]
Please let me know if there is anything that I can do at my side to get working.. I need it urgently. 
Do I need to add any permissions in the Android Manifest?

**Comment by olokobayusuf** [comment]
> Please let me know if there is anything that I can do at my side to get working.. I need it urgently.
> Do I need to add any permissions in the Android Manifest?

Hey there sorry for the late response on this. Can you upload the full, unfiltered logs from logcat in a .txt file?

**Comment by SimarjitSeasia** [comment]
Hi, I have attached the logs file from the logcat. Please find it below in the attachments. I have used Unity Android logcat from the package manager. 
Thanks
[logcats.docx](https://github.com/natsuite/NatStep/files/5787244/logcats.docx)

**Comment by olokobayusuf** [comment]
Apparently the pedometer is properly initialized. There are no errors. I'll look into this.

**Comment by SimarjitSeasia** [comment]
A thing to be noted, when I import the unity.package every time  I am not able to build the apk for Android because the iOS platform is not included automatically on libPedometer.a file. It is set to "Any platform" then I unchecked it and checked it for iOS and restarted Unity only then I was able to make a build. Could this be a reason? I may have changed some settings unknowingly.

**Comment by olokobayusuf** [comment]
> A thing to be noted, when I import the unity.package every time I am not able to build the apk for Android because the iOS platform is not included automatically on libPedometer.a file. It is set to "Any platform" then I unchecked it and checked it for iOS and restarted Unity only then I was able to make a build. Could this be a reason? I may have changed some settings unknowingly.

No that has nothing to do with it. The logs show that the pedometer was initialized properly.

**Comment by SimarjitSeasia** [comment]
Hey, Are you able to diagnose the issue?

**Comment by CSaratakij** [comment]
You need to ask runtime permission for Android 10
android.permission.ACTIVITY_RECOGNITION
https://developer.android.com/about/versions/10/privacy/changes#physical-activity-recognition
