### ISSUE TITLE
Find system steps on IOS

### ISSUE THREAD

**Issue by jacquesfeng123** [natsuite/NatStep#16]
Hi, 

So I am looking for a way to record steps the user is using everyday. Obviously I can't be calculating on the APP since it will be killed.

Since I know this is possible on ANDROID, I did some modification and managed to get the system stepCount of android based on your plugin. Works very well on all the android phones I have tried with. i.e. user has recorded 10 steps, now opens the app, shows 10 steps, and records 5 more steps, now it shows 15 steps.

However with IOS, I can only read the steps calculated since APP opening.i.e. user has recorded 10 steps, now opens the app, shows 0 steps, and records 5 more steps, now it shows 0 steps.

Any advice? Is IOS capable of getting the same data?

**Comment by olokobayusuf** [comment]
Hey @jacquesfeng123 , I'm curious about how you were able to get historical step data. iOS allows you to set a start date for step events, but my issue is coming up with a way to standardize this across both iOS and Android.
