### ISSUE TITLE
App does not install on android.

### ISSUE THREAD

**Issue by elblogbruno** [natsuite/NatStep#6]
I tried installing by builded apk and says "App is not installed".
Using Android Oreo 8.0 and unity 2018.1.0f2

**Comment by olokobayusuf** [comment]
Can you share more information? Can you confirm that this issue is because of Pedometer API?

**Comment by elblogbruno** [comment]
I'll check It Tomorrow is late in my country
Thanks for answering so fast!

**Comment by elblogbruno** [comment]
I didn't have space on my phone
I deleted some apps and restarted my phone
Voila! Everything's working!
