### ISSUE TITLE
Cannot find 'Pedometer'

### ISSUE THREAD

**Issue by chiragpranami** [natsuite/NatStep#8]
The type or namespace name 'Pedometer' could not be found (are you missing a using directive or an assembly reference?)

**Comment by olokobayusuf** [comment]
Make sure to use the namespace:
https://github.com/olokobayusuf/Pedometer-API/blob/e3cce08e8a571adda65f1c0b63534817c51a8791/Assets/Pedometer/Plugins/Managed/Pedometer.cs#L5-L13

**Comment by jacquesfeng123** [comment]
Hi,

I don't get how to use this api. is there a package to add? 

I also get the above problem and don't know how to use your answer

**Comment by olokobayusuf** [comment]
@jacquesfeng123 have you imported [the unitypackage](https://github.com/olokobayusuf/Pedometer-API/releases/tag/1.1-builds)? Once you do, make sure to use the namespace, `PedometerU`. If namespaces don't sound familiar, [look at the C# reference on the topic](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/namespaces/).
